version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
