version: 2.1
jobs:
  test_and_deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Install Rsync
          command: sudo apt-get update && sudo apt-get install rsync
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test
      - run: 
          name: Building
          command: npm run build
      - run: 
          name: dir list
          command: ls /public

workflows:
  version: 2.1
  test_and_build:
    jobs:
      - test_and_deploy
      
